# Providers :- discover the services that live on your infrastructure (their IP, health, ...)
# Entrypoints :- listen for incoming traffic (ports, ...)
# Routers :- analyse the requests (host, path, headers, SSL, ...). A router is in charge of connecting incoming requests to the services that can handle them.
# Services :- forward the request to your services (load balancing, ...). The Services are responsible for configuring how to reach the actual services that will eventually handle the incoming requests.
# Middlewares :- may update the request or make decisions based on the request (authentication, rate limiting, headers, ...)


version: "3.7"

networks:
  test-network:
    external: true
    name: test-network

services:
  traefik:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.hostname == gcloud1
          - node.role == manager
      labels:
        - "traefik.enable=true"

    secrets:
      - source: custom_crt
        target: /run/secrets/server.crt
        mode: 0400

      - source: custom_key
        target: /run/secrets/server.key
        mode: 0400

    hostname: traefik
    image: "traefik:v2.1"
    #user: "${UID}:1002"

     #Static configuration
    command:
      - --providers.file.filename=/etc/traefik/proxy-config.toml # Using file for reading the config
      - --providers.file.watch=true

      - --entrypoints.web.address=:6060
      - --entrypoints.websecure.address=:443
      #- --api.insecure # enabling dashboard on insecure connection
      - --api=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG

      #lets encrypt : for production by default url is "https://acme-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=myemail@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=acme.json
      - --certificatesresolvers.myresolver.acme.tlschallenge=true

    volumes:
      - ./proxy-config.toml:/etc/traefik/proxy-config.toml:ro
        #- /home/prayag/GoWorkspace/src/github.com/test/certs/:/etc/traefik/certs:ro  <-- was giving permission error in logs hence I switched to docker secrets
      - letsencrypt:/letsencrypt/acme.json:wo

    ports:
      - target: 6060
        published: 6060
        #protocol: tcp
        mode: host
      - target: 443
        published: 443
        #protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        #protocol: tcp
        mode: ingress # traefik dashboard

    networks:
      - test-network

volumes:
  letsencrypt:

secrets:
  custom_crt:
    external: true
    name: server.crt

  custom_key:
    external: true
    name: server.key